// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfbp-sGuWMbdbUhqg5vPOk9jE066hwbZ4',
    appId: '1:886455820728:web:6a80b930f608778ce2af4d',
    messagingSenderId: '886455820728',
    projectId: 'app-pro-221dd',
    authDomain: 'app-pro-221dd.firebaseapp.com',
    storageBucket: 'app-pro-221dd.firebasestorage.app',
    measurementId: 'G-56ZGTYQ716',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBIzIrG81o7jMpCUloDq7LH89JdGsBY-U',
    appId: '1:886455820728:android:52dcc870e49f3e04e2af4d',
    messagingSenderId: '886455820728',
    projectId: 'app-pro-221dd',
    storageBucket: 'app-pro-221dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh4Pltss7sEhq43Q8ErVySuYnG21fmpHA',
    appId: '1:886455820728:ios:4f7feac9549a279fe2af4d',
    messagingSenderId: '886455820728',
    projectId: 'app-pro-221dd',
    storageBucket: 'app-pro-221dd.firebasestorage.app',
    iosBundleId: 'com.menghor.twfurniturekh',
  );
}
